### ISSUE TITLE
Weet je zker dat je hier een div wil gebruiken? Kan je een semantisch element bedenken?

### ISSUE THREAD

**Issue by joostf** [Tristandemuijnck/the-startup-responsive-interactieve-website#19]
https://github.com/Tristandemuijnck/the-startup-responsive-interactieve-website/blob/25e9747df9c460b3fd6c8daad23c2576efbe2446/index.html#L79-L82

**Comment by Tristandemuijnck** [comment]
![image](https://user-images.githubusercontent.com/43402897/213810712-9bfe31e6-b8ac-44c1-95eb-564c74bb8bc2.png)

Veranderd naar een header
