### ISSUE TITLE
Lacks heading

### ISSUE THREAD

**Issue by luukbrauckmann** [Tristandemuijnck/the-startup-responsive-interactieve-website#22]
https://github.com/Tristandemuijnck/the-startup-responsive-interactieve-website/blob/f97a98330b12f378534ecedfd7c20dafddc6968a/index.html#L94

**Comment by Tristandemuijnck** [comment]
![image](https://user-images.githubusercontent.com/43402897/214160089-19e8e929-6181-436c-a5fe-3298b154db88.png)

Added header :)
